name: Weekly ETL

on:
  schedule:
    - cron: '0 3 * * 1'  # Mondays 03:00 UTC (~04:00/03:00 UK depending on DST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install pandas pyarrow requests python-dateutil rapidfuzz tqdm

      - name: Build aggregates (smoke test)
        run: |
          python - <<'PY'
          import json
          from pathlib import Path
          from datetime import datetime, timezone

          base = Path("public/data")
          ford = base / "ford/fiesta/2013.json"
          vw   = base / "vw/polo/2013.json"
          for p in [ford, vw]:
              p.parent.mkdir(parents=True, exist_ok=True)
              data = json.loads(p.read_text()) if p.exists() else {}
              data["_ci_refreshed_at"] = datetime.now(timezone.utc).isoformat()
              p.write_text(json.dumps(data, indent=2))
